[package]
name = "hdf5-dst"
version = "0.1.0"
edition = "2021"

[dependencies]
hdf5-dst-derive = { workspace = true }
hdf5 = { workspace = true }
hdf5-sys = { workspace = true }
dst-container = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
