[package]
name = "hdf5-hl"
version = "0.1.0"
edition = "2021"

[dependencies]
hdf5-hl-sys = { path = "../hdf5-hl-sys" }
hdf5 = "0.8"
hdf5-sys = "0.8"
dst-container = "0.1"

[dev-dependencies]
tempfile = "3.3"
